-- Création de la table users
CREATE TABLE IF NOT EXISTS users (
    Patient_ID SERIAL PRIMARY KEY,
    Age INTEGER,
    Gender TEXT,
    Weight_kg NUMERIC(5,2),
    Height_cm NUMERIC(5,2),
    Disease_Type TEXT,
    Severity TEXT,
    Physical_Activity_Level TEXT,
    Daily_Caloric_Intake INTEGER,
    Cholesterol_mg_dL INTEGER,
    Blood_Pressure_mmHg TEXT,
    Glucose_mg_dL INTEGER,
    Dietary_Restrictions TEXT,
    Allergies TEXT,
    Preferred_Cuisine TEXT,
    Weekly_Exercise_Hours NUMERIC(4,2),
    Adherence_to_Diet_Plan TEXT,
    Diet_Recommendation TEXT,
    BMI_Calculated NUMERIC(5,2),
    Gym_max_bpm INTEGER,
    Gym_avg_bpm INTEGER,
    Gym_resting_bpm INTEGER,
    Gym_session_duration_hours NUMERIC(4,2),
    Gym_calories_burned INTEGER,
    Gym_workout_type TEXT,
    Gym_fat_percentage NUMERIC(5,2),
    Gym_water_intake_liters NUMERIC(5,2),
    Gym_workout_frequency_days_week INTEGER,
    Gym_experience_level TEXT,
    Gym_height_cm NUMERIC(5,2)
);
